name: NCLEXPower Dev CI/CD Build

on:
  push:
    branches:
      - mdev
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"
      - "release/*"
  pull_request:
    branches:
      - mdev
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"
      - "release/*"

jobs:
  determine_changed_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine Changed Files
        id: changed_files
        uses: actions/github-script@v6
        with:
          script: |
            const changedFiles = await github.paginate(
              github.rest.repos.compareCommits,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: github.context.payload.before,
                head: github.context.sha,
              },
              (response) => response.data.files.map((file) => file.filename)
            );
            core.setOutput('files', JSON.stringify(changedFiles));

  deploy_simulator:
    needs: determine_changed_files
    if: github.ref == 'refs/heads/mdev' && contains(needs.determine_changed_files.outputs.files, 'apps/simulator/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy simulator to Vercel (Dev)
        run: |
          cd apps/simulator
          npx vercel --prod --token ${{ secrets.NCLEX_VERCEL_TOKEN }} --scope nclex-power --project nclexpower-simulatordev

  deploy_web_customer:
    needs: determine_changed_files
    if: github.ref == 'refs/heads/mdev' && contains(needs.determine_changed_files.outputs.files, 'apps/web-customer/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy web-customer to Vercel (Dev)
        run: |
          cd apps/web-customer
          npx vercel --prod --token ${{ secrets.NCLEX_VERCEL_TOKEN }} --scope nclex-power --project nclexpowerdev

  deploy_web_backoffice_generic:
    needs: determine_changed_files
    if: github.ref == 'refs/heads/mdev' && contains(needs.determine_changed_files.outputs.files, 'apps/web-backoffice-generic/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy web-backoffice-generic to Vercel (Dev)
        run: |
          cd apps/web-backoffice-generic
          npx vercel --prod --token ${{ secrets.NCLEX_VERCEL_TOKEN }} --scope nclex-power --project nclexpower-officedev
