name: NCLEXPower Dev CI/CD Build

on:
  push:
    branches:
      - mdev
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"
      - "release/*"
  pull_request:
    branches:
      - mdev
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"
      - "release/*"

jobs:
  determine_changed_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Identify Changed Files
        id: detect_changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          cat changed_files.txt

      - name: Set Outputs for Affected Apps
        id: set_flags
        run: |
          if grep -q '^apps/web-customer/' changed_files.txt; then
            echo "::set-output name=web_customer::true"
          else
            echo "::set-output name=web_customer::false"
          fi
          if grep -q '^apps/web-backoffice-generic/' changed_files.txt; then
            echo "::set-output name=web_backoffice::true"
          else
            echo "::set-output name=web_backoffice::false"
          fi
          if grep -q '^apps/simulator/' changed_files.txt; then
            echo "::set-output name=simulator::true"
          else
            echo "::set-output name=simulator::false"
          fi

    outputs:
      web_customer: ${{ steps.set_flags.outputs.web_customer }}
      web_backoffice: ${{ steps.set_flags.outputs.web_backoffice }}
      simulator: ${{ steps.set_flags.outputs.simulator }}

  deploy_web_customer:
    needs: determine_changed_files
    if: needs.determine_changed_files.outputs.web_customer == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Web Customer to Vercel
        run: |
          cd apps/web-customer
          npx vercel --prod --token ${{ secrets.NCLEX_VERCEL_TOKEN }} --scope nclex-power --project nclexpowerdev

  deploy_web_backoffice_generic:
    needs: determine_changed_files
    if: needs.determine_changed_files.outputs.web_backoffice == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Web Backoffice Generic to Vercel
        run: |
          cd apps/web-backoffice-generic
          npx vercel --prod --token ${{ secrets.NCLEX_VERCEL_TOKEN }} --scope nclex-power --project nclexpower-officedev

  deploy_simulator:
    needs: determine_changed_files
    if: needs.determine_changed_files.outputs.simulator == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Simulator to Vercel
        run: |
          cd apps/simulator
          npx vercel --prod --token ${{ secrets.NCLEX_VERCEL_TOKEN }} --scope nclex-power --project nclexpower-simulatordev
