import { PriceButtonType } from "core-library/api/types";
import { CoreZigmaLogo, ArxeniusLogoBlue } from "core-library/assets";
import { DialogContents } from "core-library/components";

export const PriceButtonDetails: PriceButtonType[] = [
  {
    acronym: "RN",
    label: "Registered Nurse",
    value: 0,
  },
  {
    acronym: "PN",
    label: "Practical Nurse",
    value: 1,
  },
];

export const dataContent: DialogContents[] = [
  {
    id: 1,
    title: "Welcome to Arxenius Review.",
    image: "", // A placeholder image for now, preparation for resources image.
    contentType: "text",
    content:
      "Bacon ipsum dolor amet short loin turkey rump, pork flank biltong kevin chislic cow beef ribs picanha alcatra capicola venison shank. Salami brisket porchetta hamburger, pastrami doner pork chop pork flank pancetta tenderloin capicola. ",
  },
  {
    id: 2,
    title: "How to use Arxenius Review.",
    image: CoreZigmaLogo,
    contentType: "video",
    content: "https://www.youtube.com/watch?v=H2jA88pESko",
  },
  {
    id: 3,
    image: CoreZigmaLogo,
    title: "Start your journey.",
    contentType: "video",
    content: "https://www.youtube.com/watch?v=bTtkRrIlIv0",
  },
  {
    id: 4,
    image: CoreZigmaLogo,
    title: "Start the tour.",
    contentType: "text",
    content:
      "Bacon ipsum dolor amet short loin turkey rump, pork flank biltong kevin chislic cow beef ribs picanha alcatra capicola venison shank. Salami brisket porchetta hamburger, pastrami doner pork chop pork flank pancetta tenderloin capicola. ",
  },
];

export const programTopicShortHand: Record<string, string> = {
  // 1 Cardio
  Hypertension: "HTN",
  "Coronary Artery Disease": "CAD",
  "Congestive Heart Failure": "CHF",
  "Valvular Diseases": "Valve",
  Cardiomyopathy: "CMPY",
  "Pericardial Diseases": "Peri",
  "Aortic Aneurysm": "AA",
  "Peripheral Artery Disease": "PAD",
  "Peripheral Venous Disease": "PVD",
  Cholesterol: "Chol",
  "Cardiac Arrythmias (ECG)": "ECG",
  "ETC Cardiac": "ETC",
  // 2 Respi
  Asthma: "ASTH",
  "Obstructive Pulmonary Disease": "COPD",
  "Acute Respiratory Distress": "ARDS",
  "Pleural Effusion": "PEff",
  "Pulmonary Embolism": "PE",
  "Acid-Base (Respiration)": "A/B",
  "ETC Respiratory": "ETC",
  // 3 GI
  Esophagitis: "Eso",
  "Reflux Disease": "GERD",
  "Peptic Ulcer": "PUD",
  "Gallbladder Issues": "Chole",
  Pancreatitis: "PCTS",
  Hepatitis: "Hepa",
  Cirrhosis: "Cirr",
  Appendicitis: "App",
  "GI Bleeding": "GI Bleed",
  "Diverticular Diseases": "DVRT",
  "Irritable Bowel": "IBD",
  "Motility Issues": "Mot",
  "ETC Gastro": "ETC",
  // 4 Nephro
  "Chronic Kidney Disease": "CKD",
  "Acute Kidney Disease": "AKD",
  "Kidney Stones": "STN",
  "Cysts and Cancer": "C/Ca",
  "Benign Prostatic Hyperplasia": "BPH",
  Cryptorchidism: "Cryp",
  "Acid-Base Issues": "A/B",
  "Electrolyte Issues": "Ions",
  "ETC Renal/Urinary": "ETC",
  // 5 Hema
  Anemia: "Anm",
  Bleeding: "Bld",
  Thrombocytopenia: "TCP",
  Thrombophilia: "TP",
  Leukemia: "Leu",
  Polycythemia: "PCV",
  Lymphoma: "Lym",
  "ETC Hematology": "ETC",
  // 6 Infectious
  "Antibiotics Overview": "OV",
  Immunizations: "IMZ",
  "Brain Infections": "BInfx",
  "Ear Nose Throat": "ENT",
  Tuberculosis: "TB",
  Pneumonia: "PNA",
  "SARS Coronavirus": "SARS",
  Endocarditis: "Endo",
  "HIV/AIDS": "HIV",
  "Genital Infections": "STD",
  "Urinary Infections": "UTI",
  // 7 Neuro
  Stroke: "CVA",
  Seizure: "SZ",
  "Cerebral Palsy": "CP",
  "Alzheimer’s and Dementia": "AZD",
  "ALS/Lou Gehrig’s": "ALS",
  "Parkinson’s Disease": "PRD",
  Demyelination: "DMY",
  "Myasthenia Gravis": "MG",
  "Eye Ear Nose Throat": "EENT",
  "ETC Neurological": "ETC",
  // 8 Endocrine
  "Anterior Pituitary": "ANT",
  "Posterior Pituitary": "POST",
  Thyroid: "THY",
  Adrenals: "ADR",
  "Diabetes Mellitus": "DM",
  "ETC Endocrine": "ETC",
  // 10 Skin
  Dermatitis: "Drts",
  Psoriasis: "Psr",
  Urticaria: "Urt",
  Acne: "Acne",
  "Skin Infections": "Infxn",
  "ETC Integumentary": "ETC",
  // 11 Onco
  "Brain Tumors": "BTm",
  "Bone Tumors": "Bone",
  "Colon Cancer": "Colon",
  "Hepatic Cancer": "HCC",
  "Pancreatic Cancer": "PC",
  "Prostate Cancer": "PTC",
  "Lung Cancer": "LC",
  "Skin Cancer": "SC",
  "ETC Oncology": "ETC",
  // 12 OG-GYN
  "Breast Cancer": "BrCA",
  "Ovarian Cancer": "Ova",
  "Cervical Cancer": "Cerv",
  Menopause: "MNP",
  Contraceptives: "CTR",
  "ETC Gynecology": "ETC",
  // 13 Mother Baby
  Pregnancy: "ANTE",
  "Labor and Delivery": "L&D",
  "Gestational Issues": "GS",
  "Fetal Malpositions": "FET",
  "C-Section": "CS",
  "Post-partum Issues": "PP",
  "Premature Birth": "PreT",
  Hyperbilirubinemia: "HypB",
  Hydrocephalus: "Hydro",
  "Congenital Heart Issues": "CHD",
  // 14 Pediatrics
  Neonate: "NEO",
  "Age Development": "Dev",
  Immunization: "IMZ",
  "Respiratory Issues": "Respi",
  "Cardiovascular Issues": "Cardio",
  "GI Issues": "GI",
  "Endocrine Issues": "Endo",
  "Neurological Issues": "Neuro",
  "Pediatric Issues": "ETC",
  // 15 Medical Surgery
  Assessment: "ASM",
  "Gait and Crutches": "ASW",
  Traction: "Trac",
  "Pressure Sores": "Ulcer",
  "Wound Care": "WC",
  Restraints: "Res",
  Nutrition: "Food",
  "Herbal Supplements": "Herb",
  "IV Therapy": "IV",
  "Clinical Signs": "Abrv",
  "Food-Drug Interactions": "FDI",
  "Medication Administration": "Rx",
  "Common Diagnostics": "Dx",
  // Critical Care
  Hemodynamics: "HDM",
  "Tubes and Drains": "TDr",
  "Oxygen and Ventilators": "Vent",
  "Perioperative Care": "Ops",
  "Blood Products": "Blood",
  // Emergency
  "Cardiac Arrest": "CArr",
  Shock: "SHK",
  Syncope: "Sync",
  Burns: "Burn",
  "Bites and Stings": "Bite",
  Frostbite: "Frost",
  "Brain Injuries": "Brain",
  "Spinal Cord Injury": "Spine",
  Fractures: "Frac",
  "Diabetic Emergencies": "DM-E",
  "Endocrine Emergencies": "Endo",
  "Respiratory Emergencies": "Resp",
  Poisoning: "PSN",
  "OB Emergencies": "OB-E",
  // Mental Health
  "Therapeutic Communication": "TC",
  "Anxiety Disorders": "AD",
  "Mood Disorders": "MD",
  "Psychotic Disorders": "Psy",
  "Personality Disorders": "Pers",
  "Attention-deficit Disorder": "ADHD",
  "Autism Spectrum": "ASD",
  "Substance Abuse": "Subst",
  Medications: "ETC",
  // Nurse Station
  "Nursing Ethics": "NE",
  "Nursing Delegation": "Deleg",
  Prioritization: "Pri",
  Culture: "Cltr",
  Leadership: "Lead",
};
